name: gmdsitut
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pandas<2.0
  - numpy 
  - matplotlib 
  - jupyter 
  - notebook 
  - scipy 
  - shapely
  - rtree
  - pyproj>=2.0
  - pyshp
  - psutil
  - git
  - nbconvert
#  - pip:
#      - flopy
#      - pyemu


